// Quick test to output the exact permutation generated by C# for a given key+grid
// Run: dotnet script TestScramble.csx

var key = "126f08b45659f7d65e91dbcb2e680a9908fb54ce";
var grid = 6;

// FNV-1a hash
uint hash = 2166136261;
foreach (char c in key)
{
    hash ^= c;
    hash *= 16777619;
}
int seed = (int)(hash & 0x7FFFFFFF);
Console.WriteLine($"Key: {key}");
Console.WriteLine($"Grid: {grid}");
Console.WriteLine($"Seed: {seed}");

// Generate permutation with System.Random
int totalTiles = grid * grid;
var indices = Enumerable.Range(0, totalTiles).ToArray();
var rng = new Random(seed);

// Fisher-Yates shuffle
for (int i = totalTiles - 1; i > 0; i--)
{
    int j = rng.Next(i + 1);
    (indices[i], indices[j]) = (indices[j], indices[i]);
}

Console.WriteLine($"Permutation: [{string.Join(", ", indices)}]");

// Also output inverse
var inverse = new int[totalTiles];
for (int i = 0; i < totalTiles; i++)
    inverse[indices[i]] = i;
Console.WriteLine($"Inverse: [{string.Join(", ", inverse)}]");
